export const routes = {
  home: '/',
  login: '/login',
  clientes: '/clientes',
  cliente: (id: string) => `/clientes/${id}`,
  produtos: '/produtos',
  pedidos: '/pedidos',
  pedidosFiltrados: (status: string) => `/pedidos?status=${status}`,
  novoPedido: '/pedidos/novo',
  pedido: (id: string) => `/pedidos/${id}`,
  orcamento: (id: string) => `/pedidos/${id}/orcamento`,
  agenda: '/agenda',
  relatorios: '/relatorios',
  equipe: '/equipe',
} as const
